---
- hosts: all
  become: true

- hosts: all
  become: true
  tasks:
    - name: create epomeroy user
      user:
        name: epomeroy
        shell: /bin/bash

    - name: add terra ssh key for epomeroy
      authorized_key:
        user: epomeroy
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGnW2dkO+xoxwxrNKeomjUm3xWaNlBA/upF3rlf3YbSl epomeroy@terra"

    - name: add callisto ssh key for epomeroy
      authorized_key:
        user: epomeroy
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINWGjIixGg5xru1ORmSZA5gHppTqaBO8gALHFNeo/WJl epomeroy@callisto"

    - name: add sudoers file for epomeroy
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/epomeroy
        line: "epomeroy ALL=(ALL) NOPASSWD: ALL"
        state: present
        mode: 0440
        create: true
        validate: "visudo -cf %s"
