---
- name: boostrap

- hosts: all
  become: true

- hosts: all
  become: true
  tasks:
    - name: Create jpomeroy user
      ansible.builtin.user:
        name: jpomeroy
        shell: /bin/bash

    - name: Add terra ssh key for jpomeroy
      ansible.builtin.authorized_key:
        user: jpomeroy
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGnW2dkO+xoxwxrNKeomjUm3xWaNlBA/upF3rlf3YbSl jpomeroy@terra"

    - name: Add callisto ssh key for jpomeroy
      ansible.builtin.authorized_key:
        user: jpomeroy
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINWGjIixGg5xru1ORmSZA5gHppTqaBO8gALHFNeo/WJl jpomeroy@callisto"

    - name: Add sudoers file for jpomeroy
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/jpomeroy
        line: "jpomeroy ALL=(ALL) NOPASSWD: ALL"
        state: present
        mode: 0440
        create: true
        validate: "visudo -cf %s"
