---
- name: Common tasks
  hosts: all
  roles:
    - common

- name: HAProxy tasks
  hosts: haproxy
  roles:
    - haproxy

- name: Jenkins tasks
  hosts: jenkins
  roles:
    - jenkins

- name: K3S common tasks
  hosts:
    - k3s_node
    - k3s_server
  roles:
    - k3s_common

- name: K3S server tasks
  hosts: k3s_server
  roles:
    - k3s_common
    - k3s_server

- name: K3S node tasks
  hosts: k3s_node
  roles:
    - k3s_common
    - k3s_node

- name: K3S reset node tasks
  hosts: k3s_node
  roles:
    - k3s_reset

- name: Name server tasks
  hosts: ns
  roles:
    - ns

- name: NFS tasks
  hosts: nfs
  roles:
    - nfs

- name: RP3  tasks
  hosts: rp3
  roles:
    - rp3

- name: RP4 tasks
  hosts: rp4
  roles:
    - rp4
