---
- name: Shutdown host # noqa no-changed-when
  community.general.shutdown:
    delay: 5
  when: ansible_facts['os_family'] == "Debian"

- name: Wait for the host to go down
  ansible.builtin.wait_for:
    host: "{{ ansible_ssh_host }}"
    port: 22
    state: stopped
  delegate_to: localhost
