---
- name: Update boot config.txt file
  tags: rp4
  ansible.builtin.copy:
    src: config.txt
    dest: /boot/config.txt
    owner: root
    group: root
    mode: 0755
  notify: Restart boot config
