---
- name: Stop named server
  ansible.builtin.systemd:
    name: bind9
    state: stopped
  listen: restart named

- name: Find named jnl bind files
  ansible.builtin.find:
    paths: /var/lib/bind
    patterns: "*.jnl"
  register: files_to_delete
  listen: restart named

- name: Remove named jnl bind files
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ files_to_delete.files }}"
  listen: restart named

- name: Restart named server
  ansible.builtin.systemd:
    name: bind9
    state: restarted
  listen: restart named

- name: Reload named server
  ansible.builtin.systemd:
    name: bind9
    state: reloaded
  listen: restart named

- name: Restart DHCPD server
  ansible.builtin.systemd:
    name: isc-dhcp-server
    state: restarted
  listen: restart dhcpd
